### ISSUE TITLE
ESP8266 / nodemcu

### ISSUE THREAD

**Issue by 4noxx** [btodcox/BBQduino#1]
is it possible to run BBQduino on a nodemcu?

wlan support would be nice

**Comment by btodcox** [comment]
I agree about wifi support being needed. 

I did some preliminary work to port this project to ESP8266 Arduino and found that the firmware that runs on the ESP8266 would not allow the measurement of the precise timing of the received temperature signal.   Based on this, it would appear the best way to get wifi support is to use an Arduino Uno to decode the temp data and then pass the data to a nodemcu or ESP8266 programmed as a wifi bridge (using something like https://github.com/beckdac/ESP8266-transparent-bridge)  via the serial port.    Have it on the todo list, but not likely to get to it in the near term.
